# Generated by Django 4.1.3 on 2022-11-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('fullname', models.CharField(max_length=200)),
                ('enname', models.CharField(max_length=200)),
                ('market', models.CharField(max_length=200)),
                ('exchange', models.CharField(max_length=200)),
                ('curr_type', models.CharField(max_length=200)),
                ('list_status', models.CharField(max_length=200)),
                ('list_date', models.CharField(max_length=200)),
                ('delist_date', models.CharField(max_length=200)),
                ('is_hs', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('-update_time',),
            },
        ),
    ]
