# Generated by Django 4.1.3 on 2022-11-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ts_code', models.CharField(max_length=9, unique=True, verbose_name='TS代码')),
                ('symbol', models.CharField(max_length=6, unique=True, verbose_name='股票代码')),
                ('name', models.CharField(max_length=4, verbose_name='股票名称')),
                ('area', models.CharField(max_length=3, null=True, verbose_name='地域')),
                ('industry', models.CharField(max_length=4, null=True, verbose_name='所属行业')),
                ('fullname', models.CharField(max_length=40, verbose_name='股票全称')),
                ('enname', models.CharField(max_length=80, verbose_name='英文全称')),
                ('cnspell', models.CharField(max_length=4, verbose_name='拼音缩写')),
                ('market', models.CharField(max_length=4, verbose_name='市场类型')),
                ('exchange', models.CharField(max_length=4, verbose_name='交易所代码')),
                ('curr_type', models.CharField(max_length=6, verbose_name='交易货币')),
                ('list_status', models.CharField(max_length=1, verbose_name='上市状态')),
                ('list_date', models.CharField(max_length=8, verbose_name='上市日期')),
                ('delist_date', models.CharField(max_length=8, null=True, verbose_name='退市日期')),
                ('is_hs', models.CharField(max_length=1, null=True, verbose_name='是否沪深港通标的')),
            ],
            options={
                'ordering': ('-update_time',),
            },
        ),
    ]
