# Generated by Django 4.1.3 on 2022-11-13 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ts_code', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='TS代码')),
                ('symbol', models.CharField(db_index=True, max_length=6, verbose_name='股票代码')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='股票名称')),
                ('area', models.CharField(max_length=20, null=True, verbose_name='地域')),
                ('industry', models.CharField(max_length=4, null=True, verbose_name='所属行业')),
                ('fullname', models.CharField(max_length=40, verbose_name='股票全称')),
                ('enname', models.CharField(max_length=80, verbose_name='英文全称')),
                ('cnspell', models.CharField(max_length=20, verbose_name='拼音缩写')),
                ('market', models.CharField(max_length=20, verbose_name='市场类型')),
                ('exchange', models.CharField(max_length=20, verbose_name='交易所代码')),
                ('curr_type', models.CharField(max_length=20, verbose_name='交易货币')),
                ('list_status', models.CharField(max_length=1, verbose_name='上市状态')),
                ('list_date', models.CharField(max_length=8, verbose_name='上市日期')),
                ('delist_date', models.CharField(max_length=8, null=True, verbose_name='退市日期')),
                ('is_hs', models.CharField(max_length=1, null=True, verbose_name='是否沪深港通标的')),
            ],
            options={
                'ordering': ('-update_time',),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(verbose_name='时间')),
                ('price', models.FloatField(verbose_name='当前价格')),
                ('pre_close', models.FloatField(null=True, verbose_name='昨日收盘价')),
                ('open', models.FloatField(null=True, verbose_name='开盘价')),
                ('high', models.FloatField(null=True, verbose_name='最高价')),
                ('low', models.FloatField(null=True, verbose_name='最低价')),
                ('incr_limit', models.FloatField(null=True, verbose_name='涨停价')),
                ('drop_limit', models.FloatField(null=True, verbose_name='跌停价')),
                ('chg', models.FloatField(null=True, verbose_name='涨跌')),
                ('pct_chg', models.FloatField(max_length=8, null=True, verbose_name='涨跌幅')),
                ('vol', models.FloatField(null=True, verbose_name='成交量(手)')),
                ('amount', models.FloatField(null=True, verbose_name='成交额(万)')),
                ('turnover_rate', models.FloatField(max_length=8, null=True, verbose_name='换手率')),
                ('total_mv', models.FloatField(null=True, verbose_name='总市值')),
                ('circ_mv', models.FloatField(null=True, verbose_name='流通市值')),
                ('stock', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stock.stock')),
            ],
            options={
                'ordering': ('-update_time',),
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
