# Generated by Django 4.1.3 on 2022-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='area',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='curr_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delist_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='enname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fullname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_hs',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='list_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='list_status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ts_code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
