# Generated by Django 4.1.3 on 2022-11-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='enname',
            field=models.CharField(max_length=200, verbose_name='英文全称'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fullname',
            field=models.CharField(max_length=100, verbose_name='股票全称'),
        ),
    ]
