# Generated by Django 4.1.3 on 2022-11-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='area',
            field=models.CharField(max_length=20, null=True, verbose_name='地域'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cnspell',
            field=models.CharField(max_length=20, verbose_name='拼音缩写'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='curr_type',
            field=models.CharField(max_length=20, verbose_name='交易货币'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(max_length=20, verbose_name='交易所代码'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(max_length=20, verbose_name='市场类型'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=20, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
