# Generated by Django 4.1.3 on 2022-11-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_area_alter_stock_cnspell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=6, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ts_code',
            field=models.CharField(db_index=True, max_length=9, unique=True, verbose_name='TS代码'),
        ),
    ]
