# Generated by Django 4.1.3 on 2022-11-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_area_alter_stock_curr_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='delist_date',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
