# Generated by Django 4.1.3 on 2022-11-12 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_name_alter_stock_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('date', models.DateField(verbose_name='时间')),
                ('price', models.FloatField(verbose_name='当前价格')),
                ('pre_close', models.FloatField(null=True, verbose_name='昨日收盘价')),
                ('open', models.FloatField(null=True, verbose_name='开盘价')),
                ('high', models.FloatField(null=True, verbose_name='最高价')),
                ('low', models.FloatField(null=True, verbose_name='最低价')),
                ('incr_limit', models.FloatField(null=True, verbose_name='涨停价')),
                ('drop_limit', models.FloatField(null=True, verbose_name='跌停价')),
                ('chg', models.FloatField(null=True, verbose_name='涨跌')),
                ('pct_chg', models.CharField(max_length=8, null=True, verbose_name='涨跌幅')),
                ('vol', models.FloatField(null=True, verbose_name='成交量(手)')),
                ('amount', models.FloatField(null=True, verbose_name='成交额(万)')),
                ('turnover_rate', models.CharField(max_length=8, null=True, verbose_name='换手率')),
                ('total_mv', models.FloatField(null=True, verbose_name='总市值')),
                ('circ_mv', models.FloatField(null=True, verbose_name='流通市值')),
                ('stock', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stock.stock')),
            ],
            options={
                'ordering': ('-update_time',),
            },
        ),
    ]
