# Generated by Django 4.1.3 on 2022-11-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_area_alter_stock_curr_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pinyin',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
