# Generated by Django 4.1.3 on 2022-11-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_quote'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('stock', 'date')},
        ),
    ]
