# Generated by Django 4.1.3 on 2022-11-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_quote_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='pct_chg',
            field=models.FloatField(max_length=8, null=True, verbose_name='涨跌幅'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='turnover_rate',
            field=models.FloatField(max_length=8, null=True, verbose_name='换手率'),
        ),
    ]
