version: "3"
services:
  postgres:
    image: postgres:14.5-alpine
    container_name: tk_postgres
    restart: always
    #    ports:
    #      - "127.0.0.1:15432:5432/tcp"
    environment:
      POSTGRES_DB: toolkit
      POSTGRES_PASSWORD: "toolkit"
      POSTGRES_USER: toolkit
    volumes:
      - "./volumes/postgresql:/var/lib/postgresql/data"
  mongo:
    image: mongo:4.2.9
    container_name: tk_mongo
    restart: always
    #    ports:
    #      - "127.0.0.1:17017:27017/tcp"
    volumes:
      - "./volumes/database/mongodb:/data/db"
      # - "./data/mongo-entrypoint:/docker-entrypoint-initdb.d"
  redis:
    image: redis:6.2.6
    container_name: tk_redis
    restart: always
    #    ports:
    #      - "127.0.0.1:16379:6379/tcp"
    volumes:
      - "./volumes/database/redis:/data"
  server:
    image: tk_server:latest
    container_name: tk_server
    restart: always
    #    ports:
    #      - "80:8000"
    volumes:
      - "./volumes/collectstatic:/collectstatic"
  openresty:
    image: tk_openresty:latest
    container_name: tk_openresty
    restart: always
    depends_on:
      - mongo
      - redis
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/collectstatic:/openresty/collectstatic"
