version: "3"
services:
  postgres:
    image: postgres:14.5-alpine
    container_name: tool_postgres
    restart: always
    ports:
      - "127.0.0.1:55432:5432/tcp"
    environment:
      POSTGRES_DB: toolkit
      POSTGRES_PASSWORD: "toolkit"
      POSTGRES_USER: toolkit
    volumes:
      - "./volumes/postgresql:/var/lib/postgresql/data"
  mongo:
    image: mongo:4.2.9
    container_name: tool_mongo
    restart: always
    ports:
      - "127.0.0.1:57017:27017/tcp"
    volumes:
      - "./volumes/database/mongodb:/data/db"
      # - "./data/mongo-entrypoint:/docker-entrypoint-initdb.d"
  redis:
    image: redis:6.2.6
    container_name: tool_redis
    restart: always
    ports:
      - "127.0.0.1:56379:6379/tcp"
    volumes:
      - "./volumes/database/redis:/data"
