# Generated by Django 4.1.3 on 2022-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('trigger', models.CharField(max_length=8)),
                ('config', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=200)),
                ('actor_name', models.CharField(max_length=1024)),
                ('kwargs', models.JSONField(default=dict)),
                ('priority', models.PositiveIntegerField(default=None)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-create_time',),
            },
        ),
    ]
